app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'CategoryController@index');

    Route::auth();

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
        Route::get('/', 'AdminController@index');

        Route::resource('categories', 'CategoryAdminController', ['except' =>
            ['show']
        ]);

        Route::resource('feeds', 'FeedAdminController', ['except' =>
            ['show']
        ]);
    });
});

app/Feed.php
<?php

namespace SneakerNews;

use Illuminate\Database\Eloquent\Model;

use SneakerNews\Post;

class Feed extends Model
{
    protected $fillable = [
        'name',
        'url',
        'category_id',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

	public function posts()
    {
    	return $this->hasMany(Post::class)->latest('publish_date');
    }

    public function latestPosts()
    {
        return $this->hasMany(Post::class)->latest('publish_date')->limitByForeignKey('feed_id', '10');
    }
}

resources/views/admin/feeds/_fields.blade.php
<div class='form-group'>
  <label for='name' class='col-md-2 control-label'><span class='required'>*</span> Name:</label>
  <div class='col-md-4'>
    {!! Form::text('name', $feed->name, ['class' => 'form-control']) !!}
  </div>
</div>

<div class='form-group'>
  <label for='url' class='col-md-2 control-label'><span class='required'>*</span> URL:</label>
  <div class='col-md-4'>
    {!! Form::text('url', $feed->url, ['class' => 'form-control']) !!}
  </div>
</div>

<div class='form-group'>
  <label for='category_id' class='col-md-2 control-label'><span class='required'>*</span> Category:</label>
  <div class='col-md-4'>
    {!! Form::select('category_id', $categories, $feed->category_id, ['class' => 'form-control']) !!}
  </div>
</div>

<div class='form-group'>
  <div class='col-md-10 col-md-offset-2'>
    {!! Form::submit($submitLabel, ['class' => 'btn btn-default']) !!}
  </div>
</div>

resources/views/admin/feeds/create.blade.php
@extends('layouts.app')

@section('content')

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <h3>New Feed</h3>

      @include('common._form-errors')

      {!! Form::open(['route' => 'admin.feeds.store', 'class' => 'form-horizontal']) !!}

      @include('admin.feeds._fields', ['submitLabel' => 'Save Feed'])

      {!! Form::close() !!}
    </div>
  </div>
</div>

@endsection

resources/views/admin/feeds/edit.blade.php
@extends('layouts.app')

@section('content')

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <h3>Feed: {{ $feed->name }}</h3>

      @include('common._form-errors')

      {!! Form::open(['method' => 'PUT', 'route' => ['admin.feeds.update', $feed->id], 'class' => 'form-horizontal']) !!}

      @include('admin.feeds._fields', ['submitLabel' => 'Update Feed'])

      {!! Form::close() !!}

      <div class='form-group'>
        <div class='col-md-12 text-right'> {!! Form::open(['method' => 'DELETE', 'route' => ['admin.feeds.destroy', $feed->id], 'class' => 'delete-form']) !!}
          {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs']) !!}
          {!! Form::close() !!}
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/admin/feeds/index.blade.php
@extends('layouts.app')

@section('content')

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <h3>Feeds</h3>

      @include('common._flashed-message')

      <p>
        <a href="{{ route('admin.feeds.create') }}" class='btn btn-default'>Add Feed</a>
      </p>

      <table class='table table-striped table-bordered'>
        <thead>
          <tr>
            <th>Feed</th>
            <th>URL</th>
            <th width='20%'>Category</th>
            <th width='15%'>Edit</th>
          </tr>
        </thead>

        <tbody>
          @foreach ($feeds AS $feed)
            <tr>
              <td>{{ $feed->name }}</td>
              <td><a href="{{ $feed->url }}" target='_blank'><small>{{ $feed->url }}</small></a></td>
              <td>{{ $feed->category->name }}</td>
              <td><a href="{{ route('admin.feeds.edit', $feed->id) }}">Edit</a></td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

@endsection