app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'CategoryController@index');

    Route::auth();

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
        Route::get('/', 'AdminController@index');

        Route::resource('categories', 'CategoryAdminController', ['except' =>
            ['show']
        ]);

        Route::resource('feeds', 'FeedAdminController', ['except' =>
            ['show']
        ]);
    });
});

app/Category.php
<?php

namespace SneakerNews;

use Illuminate\Database\Eloquent\Model;

use SneakerNews\Feed;

class Category extends Model
{
    protected $fillable = [
        'name',
        'display_order',
    ];

    public function feeds() {
    	return $this->hasMany(Feed::class);
    }
}

app/Post.php
<?php

namespace SneakerNews;

use Illuminate\Database\Eloquent\Model;
use SneakerNews\Helpers\StringHelper;
use SneakerNews\Scopes\LimitByForeignKey;

class Post extends Model
{
    use LimitByForeignKey;

    protected $fillable = [
        'pico_id',
        'title',
        'url',
        'publish_date',
        'author',
        'content',
        'feed_id',
    ];

    /**
     * Returns content stripped of HTML and truncated
     * @return  string
     */
    public function getContentShortenedAttribute()
    {
        $content = strip_tags($this->attributes['content']);
        return StringHelper::truncateAtWord($content, 255);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace SneakerNews\Http\Controllers;

use Cache;
use Illuminate\Http\Request;

use SneakerNews\Http\Requests;
use SneakerNews\Http\Controllers\Controller;
use SneakerNews\Repositories\Eloquent\CategoryRepository;

class CategoryController extends Controller
{
    protected $categoryRepository;

    /**
     * Create a new controller instance.
     * @return void
     */
    public function __construct(CategoryRepository $categoryRepository)
    {
        $this->categoryRepository = $categoryRepository;
    }

	/**
	 * Display categories along with associated feeds and posts
	 * @param   Request  $request
	 * @return  Response
	 */
    public function index(Request $request) {
        $categories = Cache::remember('categoriesWithFeedsAndPosts', 60, function() {
            return $this->categoryRepository->with('feeds.latestPosts')->orderBy('display_order')->all();
        });

    	return view('categories.index', compact('categories'));
    }
}

resources/views/categories/_display-feeds.blade.php
<?php $feedsDisplayed = 0; ?>

@foreach ($category->feeds AS $feed)
  <div class='col-md-4 col-sm-6'>
    <h3>{{ $feed->name }}</h3>

    @if (count($feed->latestPosts) > 0)
      <ul class='list-posts'>
        @foreach ($feed->latestPosts AS $post)
          <li>
            <a href='{{ $post->url }}' class='post-link' data-content="{{ $post->content_shortened }}">{{ $post->title }}</a>
          </li>
        @endforeach
      </ul>
    @endif
  </div>

  <?php $feedsDisplayed++; ?>

  @if ($feedsDisplayed % 3 === 0)
    <div class='clearfix visible-lg-block visible-md-block hidden-sm hidden-xs'>&nbsp;</div>
  @endif

  @if ($feedsDisplayed % 2 === 0)
    <div class='clearfix visible-sm-block hidden-lg hidden-md hidden-xs'>&nbsp;</div>
  @endif
@endforeach

resources/views/categories/index.blade.php
@extends('layouts.default')

@section('content')

@foreach ($categories AS $category)
	<div class='row'>
		<div class='col-md-12'>
			<h2>{{ $category->name }}</h2>
		</div>

		@include('categories._display-feeds')
	</div>
@endforeach

@endsection