app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'CategoryController@index');

    Route::auth();

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
        Route::get('/', 'AdminController@index');

        Route::resource('categories', 'CategoryAdminController', ['except' =>
            ['show']
        ]);

        Route::resource('feeds', 'FeedAdminController', ['except' =>
            ['show']
        ]);
    });
});

app/Category.php
<?php

namespace SneakerNews;

use Illuminate\Database\Eloquent\Model;

use SneakerNews\Feed;

class Category extends Model
{
    protected $fillable = [
        'name',
        'display_order',
    ];

    public function feeds() {
    	return $this->hasMany(Feed::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace SneakerNews\Http\Controllers;

use Cache;
use Illuminate\Http\Request;

use SneakerNews\Http\Requests;
use SneakerNews\Http\Controllers\Controller;
use SneakerNews\Repositories\Eloquent\CategoryRepository;

class CategoryController extends Controller
{
    protected $categoryRepository;

    /**
     * Create a new controller instance.
     * @return void
     */
    public function __construct(CategoryRepository $categoryRepository)
    {
        $this->categoryRepository = $categoryRepository;
    }

	/**
	 * Display categories along with associated feeds and posts
	 * @param   Request  $request
	 * @return  Response
	 */
    public function index(Request $request) {
        $categories = Cache::remember('categoriesWithFeedsAndPosts', 60, function() {
            return $this->categoryRepository->with('feeds.latestPosts')->orderBy('display_order')->all();
        });

    	return view('categories.index', compact('categories'));
    }
}

resources/views/admin/categories/_fields.blade.php
<div class='form-group'>
  <label for='name' class='col-md-2 control-label'><span class='required'>*</span> Name:</label>
  <div class='col-md-4'>
    {!! Form::text('name', $category->name, ['class' => 'form-control']) !!}
  </div>
</div>

<div class='form-group'>
  <label for='display_order' class='col-md-2 control-label'><span class='required'>*</span> Order:</label>
  <div class='col-md-1'>
    {!! Form::text('display_order', $category->display_order, ['class' => 'form-control']) !!}
  </div>
</div>

<div class='form-group'>
  <div class='col-md-10 col-md-offset-2'>
    {!! Form::submit($submitLabel, ['class' => 'btn btn-default']) !!}
  </div>
</div>

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('content')

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <h3>New Category</h3>

      @include('common._form-errors')

      {!! Form::open(['route' => 'admin.categories.store', 'class' => 'form-horizontal']) !!}

      @include('admin.categories._fields', ['submitLabel' => 'Save Category'])

      {!! Form::close() !!}
    </div>
  </div>
</div>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <h3>Category: {{ $category->name }}</h3>

      @include('common._form-errors')

      {!! Form::open(['method' => 'PUT', 'route' => ['admin.categories.update', $category->id], 'class' => 'form-horizontal']) !!}

      @include('admin.categories._fields', ['submitLabel' => 'Update Category'])

      {!! Form::close() !!}

      <div class='form-group'>
        <div class='col-md-12 text-right'>
          {!! Form::open(['method' => 'DELETE', 'route' => ['admin.categories.destroy', $category->id], 'class' => 'delete-form']) !!}
          {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs']) !!}
          {!! Form::close() !!}
        </div>
      </div>

      <h4>Category Feeds</h4>

      <table class='table table-striped table-bordered'>
        <thead>
          <tr>
            <th>Feed</th>
            <th width='15%'>Edit</th>
          </tr>
        </thead>

        <tbody>
          @foreach ($category->feeds AS $feed)
            <tr>
              <td>{{ $feed->name }}</td>
              <td><a href="#">Edit</a></td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <h3>Categories</h3>

      @include('common._flashed-message')

      <p>
        <a href="{{ route('admin.categories.create') }}" class='btn btn-default'>Add Category</a>
      </p>

      <table class='table table-striped table-bordered'>
        <thead>
          <tr>
            <th>Category</th>
            <th width='15%'>Order</th>
            <th width='15%'># of Feeds</th>
            <th width='15%'>Edit</th>
          </tr>
        </thead>

        <tbody>
          @foreach ($categories AS $category)
            <tr>
              <td>{{ $category->name }}</td>
              <td>{{ $category->display_order }}</td>
              <td>{{ $category->feeds->count() }}</td>
              <td><a href="{{ route('admin.categories.edit', $category->id) }}">Edit</a></td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

@endsection